// <auto-generated />
namespace DA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class serverFk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(serverFk));
        
        string IMigrationMetadata.Id
        {
            get { return "201812131349307_serverFk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
